#### Finding the Best Markets to Advertise In
---

We're working for an an e-learning company that offers courses on programming. Most of our courses are on web and mobile development, but we also cover many other domains, like data science, game development, etc. We want to promote our product and we'd like to invest some money in advertisement. 

Our goal in this project is to find out the two best markets to advertise our product in.

The data can be found in this [GitHub repo](https://github.com/freeCodeCamp/2017-new-coder-survey)

In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns
pd.set_option("display.max_columns", 999)
sns.set()

In [2]:
url = 'https://raw.githubusercontent.com/freeCodeCamp/2017-new-coder-survey/master/clean-data/2017-fCC-New-Coders-Survey-Data.csv'

df = pd.read_csv(url, low_memory = False)
df = df.dropna(how = 'all', axis = 1)
print('Shape:', df.shape[0], 'rows x', df.shape[1], 'columns')

df.info()

Shape: 18175 rows x 136 columns
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18175 entries, 0 to 18174
Columns: 136 entries, Age to YouTubeTheNewBoston
dtypes: float64(105), object(31)
memory usage: 18.9+ MB

In [3]:
df.sample(3, random_state = 0)

,Age,AttendedBootcamp,BootcampFinish,BootcampLoanYesNo,BootcampName,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventConferences,CodeEventDjangoGirls,CodeEventFCC,CodeEventGameJam,CodeEventGirlDev,CodeEventHackathons,CodeEventMeetup,CodeEventNodeSchool,CodeEventNone,CodeEventOther,CodeEventRailsBridge,CodeEventRailsGirls,CodeEventStartUpWknd,CodeEventWkdBootcamps,CodeEventWomenCode,CodeEventWorkshops,CommuteTime,CountryCitizen,CountryLive,EmploymentField,EmploymentFieldOther,EmploymentStatus,EmploymentStatusOther,ExpectedEarning,FinanciallySupporting,FirstDevJob,Gender,GenderOther,HasChildren,HasDebt,HasFinancialDependents,HasHighSpdInternet,HasHomeMortgage,HasServedInMilitary,HasStudentDebt,HomeMortgageOwe,HoursLearning,ID.x,ID.y,Income,IsEthnicMinority,IsReceiveDisabilitiesBenefits,IsSoftwareDev,IsUnderEmployed,JobApplyWhen,JobInterestBackEnd,JobInterestDataEngr,JobInterestDataSci,JobInterestDevOps,JobInterestFrontEnd,JobInterestFullStack,JobInterestGameDev,JobInterestInfoSec,JobInterestMobile,JobInterestOther,JobInterestProjMngr,JobInterestQAEngr,JobInterestUX,JobPref,JobRelocateYesNo,JobRoleInterest,JobWherePref,LanguageAtHome,MaritalStatus,MoneyForLearning,MonthsProgramming,NetworkID,Part1EndTime,Part1StartTime,Part2EndTime,Part2StartTime,PodcastChangeLog,PodcastCodeNewbie,PodcastCodePen,PodcastDevTea,PodcastDotNET,PodcastGiantRobots,PodcastJSAir,PodcastJSJabber,PodcastNone,PodcastOther,PodcastProgThrowdown,PodcastRubyRogues,PodcastSEDaily,PodcastSERadio,PodcastShopTalk,PodcastTalkPython,PodcastTheWebAhead,ResourceCodecademy,ResourceCodeWars,ResourceCoursera,ResourceCSS,ResourceEdX,ResourceEgghead,ResourceFCC,ResourceHackerRank,ResourceKA,ResourceLynda,ResourceMDN,ResourceOdinProj,ResourceOther,ResourcePluralSight,ResourceSkillcrush,ResourceSO,ResourceTreehouse,ResourceUdacity,ResourceUdemy,ResourceW3S,SchoolDegree,SchoolMajor,StudentDebtOwe,YouTubeCodeCourse,YouTubeCodingTrain,YouTubeCodingTut360,YouTubeComputerphile,YouTubeDerekBanas,YouTubeDevTips,YouTubeEngineeredTruth,YouTubeFCC,YouTubeFunFunFunction,YouTubeGoogleDev,YouTubeLearnCode,YouTubeLevelUpTuts,YouTubeMIT,YouTubeMozillaHacks,YouTubeOther,YouTubeSimplilearn,YouTubeTheNewBoston
167,27.0,0.0,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30 to 44 minutes,Poland,Poland,software development and IT,NaN,Employed for wages,NaN,NaN,NaN,0.0,male,NaN,NaN,1.0,0.0,1.0,1.0,0.0,0.0,150000.0,10.0,b7884335dbf8652f00b437d20b8e8682,f4bbb4ccaf448be0251e2cc82d8156ff,15000.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Polish,"single, never married",0.0,30.0,44b8d23a16,2017-03-09 09:32:25,2017-03-09 09:30:45,2017-03-09 09:35:27,2017-03-09 09:32:29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,1.0,"professional degree (MBA, MD, JD, etc.)",Robotics and Automation Engineering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15333,26.0,0.0,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15 to 29 minutes,India,India,software development and IT,NaN,Employed for wages,NaN,NaN,1.0,1.0,male,NaN,0.0,1.0,1.0,1.0,0.0,0.0,0.0,NaN,8.0,6514e7af4c530b056470b27d5a05e68c,cb6b109dcfd6e172aad88262cf45e143,64248.0,0.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marathi,"single, never married",30.0,27.0,59e6a9e8fc,2017-03-21 06:40:52,2017-03-21 06:37:03,2017-03-21 06:48:41,2017-03-21 06:40:58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,1.0,bachelor's degree,Computer Software Engineering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1670,40.0,0.0,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom,United Kingdom,NaN,NaN,Not working and not looking for work,NaN,NaN,NaN,NaN,male,NaN,NaN,1.0,0.0,1.0,1.0,0.0,0.0,61000.0,18.0,4ab20c7605987f605ef010e7e41dfb59,60051a55bccd6bcf75488242fe16a16f,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,freelance,NaN,NaN,NaN,English,"single, never married",0.0,2.0,6482a48d19,2017-03-10 09:31:14,2017-03-10 09:28:36,2017-03-10 09:33:09,2017-03-10 09:31:17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,"trade, technical, or vocational training",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Most of our courses are on web and mobile development, but we also cover many other domains, like data science, game development, etc. 

For the purpose of our analysis, we want to answer questions about a population of new coders that are interested in the subjects we teach. We'd like to know:

- Where are these new coders located.
- What locations have the greatest densities of new coders.
- How much money they're willing to spend on learning.

So we first need to clarify whether the data set has the right categories of people for our purpose. The JobRoleInterest column describes for every participant the role(s) they'd be interested in working in. 

If a participant is interested in working in a certain domain, it means that they're also interested in learning about that domain. 

So let's take a look at the frequency distribution table of this column and determine whether the data we have is relevant.

In [4]:
round(df['JobRoleInterest'].value_counts(normalize = True).sort_values(ascending = False) * 100, 1)

Full-Stack Web Developer                                                                                                                                                                                                                               11.8
  Front-End Web Developer                                                                                                                                                                                                                               6.4
  Data Scientist                                                                                                                                                                                                                                        2.2
Back-End Web Developer                                                                                                                                                                                                                                  2.0
  Mobile Developer                                                                                                                                                                                                                                      1.7
Game Developer                                                                                                                                                                                                                                          1.6
Information Security                                                                                                                                                                                                                                    1.3
Full-Stack Web Developer,   Front-End Web Developer                                                                                                                                                                                                     0.9
  Front-End Web Developer, Full-Stack Web Developer                                                                                                                                                                                                     0.8
  Product Manager                                                                                                                                                                                                                                       0.8
Data Engineer                                                                                                                                                                                                                                           0.8
  User Experience Designer                                                                                                                                                                                                                              0.7
  User Experience Designer,   Front-End Web Developer                                                                                                                                                                                                   0.6
  Front-End Web Developer, Back-End Web Developer, Full-Stack Web Developer                                                                                                                                                                             0.6
Back-End Web Developer,   Front-End Web Developer, Full-Stack Web Developer                                                                                                                                                                             0.5
  DevOps / SysAdmin                                                                                                                                                                                                                                     0.5
Back-End Web Developer, Full-Stack Web Developer,   Front-End Web Developer                                                                                                                                                                             0.5
Full-Stack Web Developer,   Front-End Web Developer, Back-End Web Developer                                                                                                                                                                             0.4
  Front-End Web Developer, Full-Stack Web Developer, Back-End Web Developer                                                                                                                                                                             0.4
Full-Stack Web Developer,   Mobile Developer                                                                                                                                                                                                            0.4
  Front-End Web Developer,   User Experience Designer                                                                                                                                                                                                   0.4
Back-End Web Developer, Full-Stack Web Developer                                                                                                                                                                                                        0.4
Full-Stack Web Developer, Back-End Web Developer                                                                                                                                                                                                        0.4
Back-End Web Developer,   Front-End Web Developer                                                                                                                                                                                                       0.3
Data Engineer,   Data Scientist                                                                                                                                                                                                                         0.3
Full-Stack Web Developer, Back-End Web Developer,   Front-End Web Developer                                                                                                                                                                             0.3
  Front-End Web Developer,   Mobile Developer                                                                                                                                                                                                           0.3
Full-Stack Web Developer,   Data Scientist                                                                                                                                                                                                              0.2
  Mobile Developer, Game Developer                                                                                                                                                                                                                      0.2
  Data Scientist, Data Engineer                                                                                                                                                                                                                         0.2
                                                                                                                                                                                                                                                       ...
  Front-End Web Developer,   Data Scientist,   Mobile Developer, Data Engineer, Full-Stack Web Developer,   User Experience Designer                                                                                                                    0.0
Data Engineer, Full-Stack Web Developer,   Mobile Developer                                                                                                                                                                                             0.0
  Mobile Developer, Full-Stack Web Developer, Game Developer,   User Experience Designer, Back-End Web Developer,   Front-End Web Developer                                                                                                             0.0
  User Experience Designer,   Product Manager, Full-Stack Web Developer,   Front-End Web Developer                                                                                                                                                      0.0
  Product Manager, Back-End Web Developer, Information Security                                                                                                                                                                                         0.0
Full-Stack Web Developer, Back-End Web Developer,   User Experience Designer,   Mobile Developer, Game Developer                                                                                                                                        0.0
  DevOps / SysAdmin,   Product Manager,   Mobile Developer, Full-Stack Web Developer                                                                                                                                                                    0.0
  Mobile Developer, Full-Stack Web Developer,   User Experience Designer                                                                                                                                                                                0.0
  Mobile Developer,   Product Manager,   Front-End Web Developer, Back-End Web Developer, Full-Stack Web Developer,   Data Scientist, Game Developer,   Quality Assurance Engineer,   User Experience Designer, Information Security, Data Engineer     0.0
Data Engineer,   Product Manager, Information Security,   Data Scientist,   DevOps / SysAdmin                                                                                                                                                           0.0
  DevOps / SysAdmin, Game Developer, Full-Stack Web Developer, Back-End Web Developer                                                                                                                                                                   0.0
  DevOps / SysAdmin, Game Developer, Full-Stack Web Developer, Information Security, Back-End Web Developer                                                                                                                                             0.0
Technology Management                                                                                                                                                                                                                                   0.0
  User Experience Designer,   Mobile Developer, Full-Stack Web Developer,   Front-End Web Developer,   DevOps / SysAdmin, Information Security                                                                                                          0.0
Back-End Web Developer,   User Experience Designer,   Front-End Web Developer, Full-Stack Web Developer, Information Security                                                                                                                           0.0
Desktop Applications                                                                                                                                                                                                                                    0.0
  Front-End Web Developer, Data Engineer,   Product Manager, Full-Stack Web Developer,   Data Scientist,   Mobile Developer                                                                                                                             0.0
  Front-End Web Developer, Information Security, Back-End Web Developer,   DevOps / SysAdmin,   User Experience Designer, Full-Stack Web Developer                                                                                                      0.0
  User Experience Designer,   Front-End Web Developer,   Quality Assurance Engineer, Information Architect                                                                                                                                              0.0
Back-End Web Developer, Information Security,   Front-End Web Developer                                                                                                                                                                                 0.0
  Product Manager, Information Security, Data Engineer, Back-End Web Developer, Artificial Intelligence engineer                                                                                                                                        0.0
Full-Stack Web Developer,   Data Scientist, Back-End Web Developer,   Front-End Web Developer                                                                                                                                                           0.0
Back-End Web Developer,   Data Scientist, Game Developer,   DevOps / SysAdmin,   Front-End Web Developer, Full-Stack Web Developer                                                                                                                      0.0
  Front-End Web Developer, Back-End Web Developer, Game Developer, Full-Stack Web Developer,   Data Scientist                                                                                                                                           0.0
Data Engineer,   Data Scientist,   Front-End Web Developer,   Mobile Developer, Back-End Web Developer, Full-Stack Web Developer,   User Experience Designer, IoT                                                                                       0.0
  Front-End Web Developer,   Product Manager,   Data Scientist, Information Security,   Mobile Developer, Data Engineer,   Quality Assurance Engineer                                                                                                   0.0
Full-Stack Web Developer,   Front-End Web Developer,   Mobile Developer,   Data Scientist                                                                                                                                                               0.0
Information Security,   User Experience Designer,   Mobile Developer,   Front-End Web Developer                                                                                                                                                         0.0
  Quality Assurance Engineer,   Mobile Developer,   Front-End Web Developer, Back-End Web Developer, Information Security, Full-Stack Web Developer                                                                                                     0.0
Data Engineer,   Data Scientist, Information Security                                                                                                                                                                                                   0.0
Name: JobRoleInterest, Length: 3213, dtype: float64

In [5]:
interests = df['JobRoleInterest'].dropna().str.split(',')

# number of interests per person
round(interests.apply(lambda x: len(x)).value_counts(normalize = True).sort_values(ascending = False)*100, 1)

1     31.7
3     15.9
4     15.2
5     12.0
2     10.9
6      6.7
7      3.9
8      1.8
9      1.0
10     0.5
12     0.3
11     0.2
13     0.0
Name: JobRoleInterest, dtype: float64

If people have >1 interest it is more likely to be 3 - 5 (43%)

In [6]:
# Top 20 Interests...
interests_all = pd.Series(
    [i.strip() for i in sum(interests, [])]
) # Single list without whitespace


round(interests_all.value_counts(normalize = True).sort_values(ascending = False).head(20) * 100, 1)

Full-Stack Web Developer         18.6
Front-End Web Developer          15.6
Back-End Web Developer           12.3
Mobile Developer                 10.2
Data Scientist                    7.3
Game Developer                    7.2
User Experience Designer          6.5
Information Security              5.9
Data Engineer                     5.5
DevOps / SysAdmin                 4.1
Product Manager                   3.6
Quality Assurance Engineer        2.2
Software Engineer                 0.0
Software Developer                0.0
Artificial Intelligence           0.0
Software engineer                 0.0
Desktop Application Developer     0.0
Machine Learning Engineer         0.0
Project Manager                   0.0
Research                          0.0
dtype: float64

In [7]:
# Web / Data / Mobile / Games
summary_interest = {'web':0, 'data':0, 'mobile':0}
for i in interests_all:
    i_split = i.lower().split(' ')
    for k in summary_interest.keys():
        if k in i_split:
            summary_interest[k] +=1
    
round(pd.Series(summary_interest)/len(interests_all)*100, 1)

data      12.8
mobile    10.2
web       46.5
dtype: float64

Here we can see that 12 interests in particular are the most common.

Of those, these three stand out. 

- Web development is the clear front runner with 46% across the top 3 alone.
- Data science & engineering come in at a combined 12.5%
- Mobile development takes 10%

**Location of Coders **

In [8]:
survey_df = df[(df['JobRoleInterest'].notnull()) & (df['CountryLive'].notnull())].copy()

# Number of coders
abs_freq = survey_df['CountryLive'].value_counts()
rel_freq = round(survey_df['CountryLive'].value_counts(normalize = True) * 100, 1)

# Potential revenue
survey_df['MonthsProgramming'] = survey_df['MonthsProgramming'].replace(0,1)
survey_df['money_per_month'] = survey_df['MoneyForLearning'] / survey_df['MonthsProgramming']
income = {k: survey_df[survey_df['CountryLive'] == k]['money_per_month'].sum().round(0) for k in survey_df['CountryLive'].unique()}

# Main language
lang = {}

for i in survey_df['CountryLive'].unique():
    temp = survey_df[survey_df['CountryLive'] == i]['LanguageAtHome'].value_counts(normalize = True).sort_values(ascending = False)
    lang.update({i: temp.keys()[0]}) 

# English speakers
lang_eng = {}

for i in survey_df['CountryLive'].unique():
    temp = survey_df[survey_df['CountryLive'] == i]['LanguageAtHome'].value_counts(normalize = True).sort_values(ascending = False)
    try:
        temp['English']
    except KeyError:
        lang_eng.update({i: 0})
    else:
        lang_eng.update({i:round(100 * temp['English'], 1)})

# Table
location_df = pd.DataFrame(
    data = {
        'Learners': abs_freq, 
        'Learners (%)': rel_freq, 
        'Potential revenue': income,
        'Main language spoken': lang,
        'English speakers (%)': lang_eng,
    })

location_df['Potential revenue per head'] = round(location_df['Potential revenue']  / location_df['Learners'], 0)

In [9]:
location_df.sort_values(by = 'Learners (%)', ascending = False).head(10)

,English speakers (%),Learners,Learners (%),Main language spoken,Potential revenue,Potential revenue per head
United States of America,83.4,3125,45.7,English,668718.0,214.0
India,7.9,528,7.7,Hindi,62552.0,118.0
United Kingdom,74.0,315,4.6,English,12704.0,40.0
Canada,66.0,260,3.8,English,27243.0,105.0
Poland,0.0,131,1.9,Polish,9233.0,70.0
Brazil,0.0,129,1.9,Portuguese,6243.0,48.0
Germany,8.9,125,1.8,German,5938.0,48.0
Australia,86.5,112,1.6,English,42765.0,382.0
Russia,1.0,102,1.5,Russian,22485.0,220.0
Ukraine,0.0,89,1.3,Russian,4291.0,48.0

Looking at this data from a total learners POV - it would be best to target:

1. USA
2. India
3. UK
4. Canada
5. Poland

In [10]:
location_df.sort_values(by = 'Potential revenue', ascending = False).head(10)

,English speakers (%),Learners,Learners (%),Main language spoken,Potential revenue,Potential revenue per head
United States of America,83.4,3125,45.7,English,668718.0,214.0
India,7.9,528,7.7,Hindi,62552.0,118.0
Spain,6.5,77,1.1,Spanish,51781.0,672.0
Australia,86.5,112,1.6,English,42765.0,382.0
Puerto Rico,14.3,7,0.1,Spanish,30040.0,4291.0
Canada,66.0,260,3.8,English,27243.0,105.0
Russia,1.0,102,1.5,Russian,22485.0,220.0
Nigeria,57.1,84,1.2,English,17086.0,203.0
Austria,5.9,17,0.2,German,14979.0,881.0
United Kingdom,74.0,315,4.6,English,12704.0,40.0

In [11]:
survey_df[['MoneyForLearning','MonthsProgramming']]

       MoneyForLearning  MonthsProgramming
1                  80.0                6.0
2                1000.0                5.0
3                   0.0                5.0
4                   0.0               24.0
6                   0.0               12.0
9                 100.0               18.0
11                  0.0                1.0
13                  NaN                NaN
14                  NaN                9.0
15                  0.0                1.0
16                200.0               12.0
18                500.0               14.0
19                500.0               28.0
21                300.0                3.0
22               4000.0               14.0
23                200.0                2.0
28                 29.0               12.0
29                300.0                NaN
30                200.0                3.0
31                  0.0                1.0
32                600.0                6.0
33                500.0                6.0
34                  NaN                NaN
35                  0.0               25.0
37                  NaN                NaN
40                200.0                8.0
41                  0.0               32.0
42                100.0                2.0
43                  0.0                5.0
52                  0.0               12.0
...                 ...                ...
18080              50.0                2.0
18081               NaN               12.0
18088             364.0                2.0
18089               0.0                2.0
18090               0.0                1.0
18093            1000.0               36.0
18097               0.0                1.0
18098              22.0               18.0
18099            1000.0                1.0
18107             550.0                2.0
18111            1000.0                5.0
18112               0.0               24.0
18113               0.0                1.0
18118               0.0               13.0
18125             200.0                7.0
18129               0.0                NaN
18130               0.0                8.0
18131             100.0                6.0
18151               0.0               22.0
18153               0.0               12.0
18154             297.0                1.0
18155               0.0                3.0
18156            1000.0                1.0
18157               0.0                1.0
18160             100.0                3.0
18161               0.0                6.0
18162               0.0               84.0
18163               0.0                NaN
18171           10000.0                1.0
18174               NaN               10.0

[6838 rows x 2 columns]

However...

If we are looking for the best total revenue potential the list is:

1. USA
2. India
3. Spain
4. Australia
5. Puerto Rico


If we take only the English speaking nations where one set of ads could be used across all locations:

1. USA
2. Australia
3. Canada
4. Nigeria
5. UK

There may be a case for targeting these locations for lower volume - higher income locations.

- E.g. we could make similar income in Spain with <100 people vs. 500 in India.